---
# - name: Uninstall old versions
#   yum: name={{ item }} state=absent
#   with_items:
#     - "docker"
#     - "docker-common"
#     - "docker-selinux"
#     - "docker-engine"

- name: Install required packages.
  yum: name={{ item }}
  with_items:
    - "yum-utils"
    - "device-mapper-persistent-data"
    - "lvm2"

- name: add docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: install docker-ce
  yum: name=docker-ce state=present

- name: Manage Docker as a non-root user
  user: name=jenkins groups=docker append=yes

- name: restart docker
  systemd:
    name: docker.service
    state: restarted
    daemon_reload: yes
    enabled: yes
