---
- name: Install Postgres yum repository
  yum: name=./roles/postgres96/files/pgdg-centos96-9.6-3.noarch.rpm state=present

- name: Install PostgreSQL client
  yum: name=postgresql state=present

- name: create password file
  template:
    src: .pgpass
    dest: /home/jenkins
    owner: jenkins
    group: jenkins
    mode: 0600
