---
- name: Setup CI Server - Jenkins and plugins
  hosts: all
  become: yes
  roles:
    # - common
    # - jenkins
    # - git
    # - gradle
    - nexus
    # - awscli
    # - packer
    # - pandoc
