---
- name: Install epel-release and pandoc
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - pandoc

- name: Check if Tex already exists
  stat: path=/usr/local/texlive/2017/bin/x86_64-linux
  register: tex_dir

- debug:
    msg: "tex_dir={{ tex_dir }}"

- name: Install module for tex installation
  yum: name={{ item }} state=present
  with_items:
    - perl-Digest-MD5
    - wget
    - python-pip
  when: tex_dir.stat.exists == false

- name: Install python expect for auto answer
  pip: name=pexpect

- name: Copy Tex Installation ISO
  copy:
    src: texlive2017-20170524.iso
    dest: /tmp/
    force: no
  when: tex_dir.stat.exists == false

- name: Mount iso
  shell: mount -o loop /tmp/texlive2017-20170524.iso /mnt/
  when: tex_dir.stat.exists == false

- name: confirm
  pause:
    prompt: |+
      TeXをインストールします。
      別のプロンプトから次のコマンドを実行してください。
        sudo /mnt/install-tl
      終了後にEnterキーを押してください。
  when: tex_dir.stat.exists == false

## 経過が表示されず、かつ、失敗することがあるため手動実行としている。
# - name: Install texlive
#   expect:
#     command: "/mnt/install-tl"
#     responses:
#       Enter command: I
#       Do you want to continue with the exact same settings as before (y/N): y
#   when: tex_dir.stdout.find("no tex") != 1
#
- name: Unount iso
  shell: umount /mnt/
  when: tex_dir.stat.exists == false

- import_tasks: add_environment_variable.yml
  with_items:
    - env_name: PATH
      env_value: /usr/local/texlive/2017/bin/x86_64-linux
    - env_name: MANPATH
      env_value: /usr/local/texlive/2017/texmf-dist/doc/man
    - env_name: INFOPATH
      env_value: /usr/local/texlive/2017/texmf-dist/doc/info
