---
- name: set timezone
  shell: timedatectl set-timezone Asia/Tokyo
  register: set_timezone
  changed_when: false

- name: set loclale
  shell: localectl set-locale LANG=ja_JP.UTF-8
  register: set_locale
  changed_when: false

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes
