---
- name: Copy the Jenkins repository definition
  copy: src=jenkins.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for JENKINS
  copy: src=RPM-GPG-KEY-JENKINS dest=/etc/pki/rpm-gpg

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes
