- name: Set Credentials
  jenkins_script:
    script: |+
      import jenkins.model.*
      import com.cloudbees.plugins.credentials.*
      import com.cloudbees.plugins.credentials.common.*
      import com.cloudbees.plugins.credentials.domains.*
      import com.cloudbees.plugins.credentials.impl.*
      import hudson.plugins.sshslaves.*;

      def global_domain = Domain.global()
      def credentials_store = Jenkins.instance.getExtensionList(
          'com.cloudbees.plugins.credentials.SystemCredentialsProvider'
      )[0].getStore()

      def credentials = new UsernamePasswordCredentialsImpl(
        CredentialsScope.GLOBAL,
        "{{ jenkins_credential.id }}",
        "Git username and password credentials",
        "{{ jenkins_credential.username }}",
        "{{ jenkins_credential.password }}",
      )
      credentials_store.addCredentials(global_domain, credentials)
  register: set_credential_result
  changed_when: set_credential_result.output.find('true') != -1
