---
- name: Install Java Development Kit
  yum: name={{ jdk }} state=present

- name: Get Jenkins repository definition
  get_url: dest=/etc/yum.repos.d/jenkins.repo url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

- name: Import Jenkins repository key
  shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum: name=jenkins state=present

- name: start jenkins
  service: name=jenkins state=started enabled=yes

- name: insert firewalld rule for http port
  firewalld: port=8080/tcp permanent=true state=enabled immediate=yes

# 一度、Jenkinsにアクセスして初期セットアップをしてからでないと実行できないのでコメントアウト
# - name: Install Jenkins Plugin
#   jenkins_plugin:
#     name: "{{ item }}"
#     params: "{{ jenkins_params }}"
#   with_items:
#     - "simple-theme-plugin"
#   notify:
#     - restart jenkins
