---
- name: Install Nginx and Tomcat
  hosts: web
  user: vagrant
  # user: root
  # user: centos
  # remote_user: root
  # remote_user: user
  become: yes
  roles:
    - common
    - nginx
    - selinux
    - tomcat
